### ISSUE TITLE
multiple lines to single line

### ISSUE THREAD

**Issue by surpavan** [Plasma/list-to-in-query#1]
Is it possible to add the feature to not only convert the values into list, but also to bring them into single like -  like a comma seperated values, by removing the line breaks.

**Comment by Plasma** [comment]
Hey there,

Can you elaborate a bit further?

At the moment we go from an input like:

```
A
B
C
```

To:

```
(
   'A',
   'B',
   'C'
)
```

Are you looking for it to instead be:

```
('A', 'B', 'C')
```

?

**Comment by surpavan** [comment]
('A', 'B', 'C') this one -  as this is the one we mostly use for sql.
Although we can have multiple options/commands to choose from too would be good.

**Comment by Plasma** [comment]
Sure, so it’s just a formatting change you’d like, as semantically they should be the same?

Thank you

**Comment by surpavan** [comment]
Yes ('A', 'B', 'C') is what I need.
But it would be great/correct if quotes are only added for text and numbers be left without quotes.
I did not check it yet since I cannot use until this single line format is there. :)

**Comment by Plasma** [comment]
Hi @surpavan 

I've pushed two new options you can find now under VS Code Extension settings for _List to SQL In Query_:

1. Keep generated IN Query (...) values on the same line (instead of separated on new lines)
1. Not quote numeric values in the IN Query (...)

Hope that helps.

**Comment by surpavan** [comment]
Hi @Plasma ,
Sure, will check them today and update you.
Thank you. 👍

**Comment by surpavan** [comment]
@Plasma - checked it.
It is working, but have to change the default option 'Join Values using New Line' is set to false.  I thought we would get a new function with this option, so that we can choose anything we want instead of changing the option continuously.

**Comment by Plasma** [comment]
@surpavan did you make the appropriate configuration change (I added a new option) in VS Code extension settings? Check that first in VS Code settings to ensure the config option is enabled

**Comment by surpavan** [comment]
yup, I am speaking of the same.  That option is working.  
I am asking if we can provide a different name for that function, so that when ever something is required we can use without editing the option file always.  Example if it is numbers or list of 2-3 elements, we would use in same line, if it is a big list generally we prefer multiline only.  In such cases, instead of editing the config we can use the different function name, which is accessible like the below one,.

![Capture](https://user-images.githubusercontent.com/37795549/74171198-2a5e2c00-4c54-11ea-8a1c-533f09fce238.JPG)

**Comment by Plasma** [comment]
Hi @surpavan I've gone ahead and changed it so these are separate commands now.

**Comment by surpavan** [comment]
@Plasma 
Thank you, that worked great.

Now I don't need any website help to convert list to a single line.
