### ISSUE TITLE
Add option to indent using spaces instead of tabs

### ISSUE THREAD

**Issue by MiConnell** [Plasma/list-to-in-query#2]
Thanks for making this extension, it saves me a lot of time every day. Would it be possible to have the option of indenting using spaces instead of tabs? I use this in a lot of Python projects and my linter always highlights the list because the indentations are done in tabs instead of spaces.

**Comment by Plasma** [comment]
Hi @MiConnell ,

I've gone ahead and added this as a feature, if you go to settings for the extension you can now use spaces over tabs for indent -- it will use your vscode tab space width setting.

Cheers

**Comment by MiConnell** [comment]
Perfect, thanks!
